CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  email varchar(255) NOT NULL UNIQUE
);

CREATE TABLE if NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  description varchar(255) NOT NULL,
  is_available bool,
  owner_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
  request_id BIGINT,
  CONSTRAINT fr_item_for_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE if NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_data TIMESTAMP WITHOUT TIME ZONE,
  end_data TIMESTAMP WITHOUT TIME ZONE,
  item_id BIGINT NOT NULL,
  booker_id BIGINT NOT NULL,
  status varchar(50),
  CONSTRAINT fk_booking_for_booker FOREIGN KEY (item_id) REFERENCES items (id),
  CONSTRAINT fk_booking_for_item FOREIGN KEY (booker_id) REFERENCES users (id)
);

--CREATE TABLE if NOT EXISTS requests (
--  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  description varchar(255) NOT NULL,
--  requestor_id BIGINT NOT NULL,
--  CONSTRAINT FOREIGN KEY (request_id) REFERENCES users (id)
--);
--
--CREATE TABLE if NOT EXISTS comments (
--  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  text varchar(255) NOT NULL,
--  item_id BIGINT NOT NULL,
--  author_id BIGINT NOT NULL,
--  CONSTRAINT FOREIGN KEY (item_id) REFERENCES items (id),
--  CONSTRAINT FOREIGN KEY (author_id) REFERENCES users (id)
--);
